/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BrazilianDebenture {
  export type DebentureTermsStruct = {
    vne: BigNumberish;
    totalSupplyUnits: BigNumberish;
    issueDate: BigNumberish;
    maturityDate: BigNumberish;
    anniversaryDay: BigNumberish;
    lockUpEndDate: BigNumberish;
    rateType: BigNumberish;
    fixedRate: BigNumberish;
    percentDI: BigNumberish;
    couponFrequencyDays: BigNumberish;
    amortType: BigNumberish;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: BytesLike;
  };

  export type DebentureTermsStructOutput = [
    vne: bigint,
    totalSupplyUnits: bigint,
    issueDate: bigint,
    maturityDate: bigint,
    anniversaryDay: bigint,
    lockUpEndDate: bigint,
    rateType: bigint,
    fixedRate: bigint,
    percentDI: bigint,
    couponFrequencyDays: bigint,
    amortType: bigint,
    isinCode: string,
    cetipCode: string,
    series: string,
    hasRepactuacao: boolean,
    hasEarlyRedemption: boolean,
    comboId: string
  ] & {
    vne: bigint;
    totalSupplyUnits: bigint;
    issueDate: bigint;
    maturityDate: bigint;
    anniversaryDay: bigint;
    lockUpEndDate: bigint;
    rateType: bigint;
    fixedRate: bigint;
    percentDI: bigint;
    couponFrequencyDays: bigint;
    amortType: bigint;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: string;
  };

  export type AmortizationEntryStruct = {
    date: BigNumberish;
    percentage: BigNumberish;
    executed: boolean;
  };

  export type AmortizationEntryStructOutput = [
    date: bigint,
    percentage: bigint,
    executed: boolean
  ] & { date: bigint; percentage: bigint; executed: boolean };

  export type CouponPaymentStruct = {
    recordDate: BigNumberish;
    paymentDate: BigNumberish;
    rateUsed: BigNumberish;
    indexValue: BigNumberish;
    couponAmount: BigNumberish;
    amortAmount: BigNumberish;
    calculated: boolean;
    paid: boolean;
  };

  export type CouponPaymentStructOutput = [
    recordDate: bigint,
    paymentDate: bigint,
    rateUsed: bigint,
    indexValue: bigint,
    couponAmount: bigint,
    amortAmount: bigint,
    calculated: boolean,
    paid: boolean
  ] & {
    recordDate: bigint;
    paymentDate: bigint;
    rateUsed: bigint;
    indexValue: bigint;
    couponAmount: bigint;
    amortAmount: bigint;
    calculated: boolean;
    paid: boolean;
  };

  export type VNARecordStruct = {
    value: BigNumberish;
    lastUpdateDate: BigNumberish;
    lastIndexValue: BigNumberish;
    accumulatedFactor: BigNumberish;
  };

  export type VNARecordStructOutput = [
    value: bigint,
    lastUpdateDate: bigint,
    lastIndexValue: bigint,
    accumulatedFactor: bigint
  ] & {
    value: bigint;
    lastUpdateDate: bigint;
    lastIndexValue: bigint;
    accumulatedFactor: bigint;
  };
}

export interface BrazilianDebentureInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "BLACKLISTED"
      | "BUSINESS_DAYS_YEAR"
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_ROLE"
      | "LOCK_UP_PERIOD"
      | "NOT_WHITELISTED"
      | "PAUSED"
      | "PRECISION_PERCENT_DI"
      | "PRECISION_PU"
      | "PRECISION_RATE"
      | "SUCCESS"
      | "TRUSTEE_ROLE"
      | "WHITELIST_ADMIN_ROLE"
      | "accumulatedDIFactor"
      | "addToBlacklist"
      | "addToWhitelist"
      | "allowance"
      | "amortizationSchedule"
      | "approve"
      | "balanceOf"
      | "batchWhitelist"
      | "blacklist"
      | "calculateNextCoupon"
      | "claimAllCoupons"
      | "claimCoupon"
      | "claimedCoupons"
      | "couponPayments"
      | "decimals"
      | "declareDefault"
      | "detectTransferRestriction"
      | "executeEarlyRedemption"
      | "executeRepactuation"
      | "getAmortizationSchedule"
      | "getCouponCount"
      | "getCouponPayment"
      | "getCurrentVNA"
      | "getPUPar"
      | "getPendingClaims"
      | "getRoleAdmin"
      | "getTerms"
      | "getVNARecord"
      | "grantRole"
      | "hasRole"
      | "isBlacklisted"
      | "isWhitelisted"
      | "issuer"
      | "lastDIUpdateDate"
      | "mature"
      | "messageForTransferRestriction"
      | "name"
      | "nextCouponIndex"
      | "oracle"
      | "pause"
      | "paused"
      | "payCoupon"
      | "paymentToken"
      | "recordCouponCalculation"
      | "removeFromBlacklist"
      | "removeFromWhitelist"
      | "renounceRole"
      | "revokeRole"
      | "setAmortizationSchedule"
      | "setOracle"
      | "status"
      | "supportsInterface"
      | "symbol"
      | "terms"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "trustee"
      | "unpause"
      | "updateDIFactor"
      | "updateVNA"
      | "vnaRecord"
      | "whitelist"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmortizationPaid"
      | "Approval"
      | "BlacklistUpdated"
      | "CouponCalculated"
      | "CouponClaimed"
      | "CouponPaid"
      | "DebentureIssued"
      | "EarlyRedemptionExecuted"
      | "Paused"
      | "RepactuationExecuted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StatusChanged"
      | "Transfer"
      | "Unpaused"
      | "VNAUpdated"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BLACKLISTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUSINESS_DAYS_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_UP_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NOT_WHITELISTED",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PAUSED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PRECISION_PERCENT_DI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISION_PU",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SUCCESS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TRUSTEE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WHITELIST_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedDIFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "amortizationSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchWhitelist",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNextCoupon",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllCoupons",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimCoupon",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedCoupons",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "couponPayments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "declareDefault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "detectTransferRestriction",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEarlyRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRepactuation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmortizationSchedule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCouponCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCouponPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentVNA",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPUPar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPendingClaims",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTerms", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVNARecord",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "issuer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastDIUpdateDate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mature", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "messageForTransferRestriction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextCouponIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payCoupon",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordCouponCalculation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmortizationSchedule",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "terms", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "trustee", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateDIFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "updateVNA", values?: undefined): string;
  encodeFunctionData(functionFragment: "vnaRecord", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BLACKLISTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUSINESS_DAYS_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_UP_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NOT_WHITELISTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PAUSED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRECISION_PERCENT_DI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRECISION_PU",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRECISION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SUCCESS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TRUSTEE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WHITELIST_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedDIFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "amortizationSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateNextCoupon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllCoupons",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCoupon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedCoupons",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "couponPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "declareDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "detectTransferRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEarlyRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRepactuation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmortizationSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCouponCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCouponPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentVNA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPUPar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTerms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVNARecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastDIUpdateDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mature", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageForTransferRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextCouponIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payCoupon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCouponCalculation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAmortizationSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "terms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trustee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDIFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateVNA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vnaRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
}

export namespace AmortizationPaidEvent {
  export type InputTuple = [
    scheduleIndex: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    scheduleIndex: bigint,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    scheduleIndex: bigint;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlacklistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouponCalculatedEvent {
  export type InputTuple = [
    couponIndex: BigNumberish,
    amount: BigNumberish,
    rateUsed: BigNumberish,
    recordDate: BigNumberish
  ];
  export type OutputTuple = [
    couponIndex: bigint,
    amount: bigint,
    rateUsed: bigint,
    recordDate: bigint
  ];
  export interface OutputObject {
    couponIndex: bigint;
    amount: bigint;
    rateUsed: bigint;
    recordDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouponClaimedEvent {
  export type InputTuple = [
    investor: AddressLike,
    couponIndex: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    couponIndex: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    investor: string;
    couponIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouponPaidEvent {
  export type InputTuple = [
    couponIndex: BigNumberish,
    totalAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    couponIndex: bigint,
    totalAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    couponIndex: bigint;
    totalAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebentureIssuedEvent {
  export type InputTuple = [
    isinCode: string,
    vne: BigNumberish,
    totalUnits: BigNumberish,
    rateType: BigNumberish
  ];
  export type OutputTuple = [
    isinCode: string,
    vne: bigint,
    totalUnits: bigint,
    rateType: bigint
  ];
  export interface OutputObject {
    isinCode: string;
    vne: bigint;
    totalUnits: bigint;
    rateType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarlyRedemptionExecutedEvent {
  export type InputTuple = [amount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [amount: bigint, timestamp: bigint];
  export interface OutputObject {
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepactuationExecutedEvent {
  export type InputTuple = [newRate: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newRate: bigint, timestamp: bigint];
  export interface OutputObject {
    newRate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedEvent {
  export type InputTuple = [
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldStatus: bigint,
    newStatus: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldStatus: bigint;
    newStatus: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VNAUpdatedEvent {
  export type InputTuple = [
    oldVNA: BigNumberish,
    newVNA: BigNumberish,
    indexValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldVNA: bigint,
    newVNA: bigint,
    indexValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldVNA: bigint;
    newVNA: bigint;
    indexValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BrazilianDebenture extends BaseContract {
  connect(runner?: ContractRunner | null): BrazilianDebenture;
  waitForDeployment(): Promise<this>;

  interface: BrazilianDebentureInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BLACKLISTED: TypedContractMethod<[], [bigint], "view">;

  BUSINESS_DAYS_YEAR: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_ROLE: TypedContractMethod<[], [string], "view">;

  LOCK_UP_PERIOD: TypedContractMethod<[], [bigint], "view">;

  NOT_WHITELISTED: TypedContractMethod<[], [bigint], "view">;

  PAUSED: TypedContractMethod<[], [bigint], "view">;

  PRECISION_PERCENT_DI: TypedContractMethod<[], [bigint], "view">;

  PRECISION_PU: TypedContractMethod<[], [bigint], "view">;

  PRECISION_RATE: TypedContractMethod<[], [bigint], "view">;

  SUCCESS: TypedContractMethod<[], [bigint], "view">;

  TRUSTEE_ROLE: TypedContractMethod<[], [string], "view">;

  WHITELIST_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  accumulatedDIFactor: TypedContractMethod<[], [bigint], "view">;

  addToBlacklist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  addToWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  amortizationSchedule: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        date: bigint;
        percentage: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  batchWhitelist: TypedContractMethod<
    [accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  blacklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  calculateNextCoupon: TypedContractMethod<
    [],
    [[bigint, bigint] & { amount: bigint; rateUsed: bigint }],
    "view"
  >;

  claimAllCoupons: TypedContractMethod<[], [bigint], "nonpayable">;

  claimCoupon: TypedContractMethod<
    [couponIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimedCoupons: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  couponPayments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        recordDate: bigint;
        paymentDate: bigint;
        rateUsed: bigint;
        indexValue: bigint;
        couponAmount: bigint;
        amortAmount: bigint;
        calculated: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  declareDefault: TypedContractMethod<[], [void], "nonpayable">;

  detectTransferRestriction: TypedContractMethod<
    [from: AddressLike, to: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  executeEarlyRedemption: TypedContractMethod<
    [redemptionPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeRepactuation: TypedContractMethod<
    [newFixedRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAmortizationSchedule: TypedContractMethod<
    [],
    [BrazilianDebenture.AmortizationEntryStructOutput[]],
    "view"
  >;

  getCouponCount: TypedContractMethod<[], [bigint], "view">;

  getCouponPayment: TypedContractMethod<
    [index: BigNumberish],
    [BrazilianDebenture.CouponPaymentStructOutput],
    "view"
  >;

  getCurrentVNA: TypedContractMethod<[], [bigint], "view">;

  getPUPar: TypedContractMethod<[], [bigint], "view">;

  getPendingClaims: TypedContractMethod<
    [investor: AddressLike],
    [[bigint, bigint] & { pendingAmount: bigint; pendingCount: bigint }],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTerms: TypedContractMethod<
    [],
    [BrazilianDebenture.DebentureTermsStructOutput],
    "view"
  >;

  getVNARecord: TypedContractMethod<
    [],
    [BrazilianDebenture.VNARecordStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isBlacklisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isWhitelisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  issuer: TypedContractMethod<[], [string], "view">;

  lastDIUpdateDate: TypedContractMethod<[], [bigint], "view">;

  mature: TypedContractMethod<[], [void], "nonpayable">;

  messageForTransferRestriction: TypedContractMethod<
    [code: BigNumberish],
    [string],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nextCouponIndex: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payCoupon: TypedContractMethod<
    [couponIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  paymentToken: TypedContractMethod<[], [string], "view">;

  recordCouponCalculation: TypedContractMethod<[], [void], "nonpayable">;

  removeFromBlacklist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  removeFromWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAmortizationSchedule: TypedContractMethod<
    [dates: BigNumberish[], percentages: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  status: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  terms: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean,
        string
      ] & {
        vne: bigint;
        totalSupplyUnits: bigint;
        issueDate: bigint;
        maturityDate: bigint;
        anniversaryDay: bigint;
        lockUpEndDate: bigint;
        rateType: bigint;
        fixedRate: bigint;
        percentDI: bigint;
        couponFrequencyDays: bigint;
        amortType: bigint;
        isinCode: string;
        cetipCode: string;
        series: string;
        hasRepactuacao: boolean;
        hasEarlyRedemption: boolean;
        comboId: string;
      }
    ],
    "view"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  trustee: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateDIFactor: TypedContractMethod<
    [diRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateVNA: TypedContractMethod<[], [void], "nonpayable">;

  vnaRecord: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        value: bigint;
        lastUpdateDate: bigint;
        lastIndexValue: bigint;
        accumulatedFactor: bigint;
      }
    ],
    "view"
  >;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BLACKLISTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUSINESS_DAYS_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LOCK_UP_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NOT_WHITELISTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAUSED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION_PERCENT_DI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION_PU"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUCCESS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRUSTEE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WHITELIST_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedDIFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addToBlacklist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "amortizationSchedule"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        date: bigint;
        percentage: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchWhitelist"
  ): TypedContractMethod<[accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateNextCoupon"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { amount: bigint; rateUsed: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimAllCoupons"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCoupon"
  ): TypedContractMethod<[couponIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedCoupons"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "couponPayments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        recordDate: bigint;
        paymentDate: bigint;
        rateUsed: bigint;
        indexValue: bigint;
        couponAmount: bigint;
        amortAmount: bigint;
        calculated: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "declareDefault"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "detectTransferRestriction"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeEarlyRedemption"
  ): TypedContractMethod<[redemptionPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeRepactuation"
  ): TypedContractMethod<[newFixedRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAmortizationSchedule"
  ): TypedContractMethod<
    [],
    [BrazilianDebenture.AmortizationEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCouponCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCouponPayment"
  ): TypedContractMethod<
    [index: BigNumberish],
    [BrazilianDebenture.CouponPaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentVNA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPUPar"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingClaims"
  ): TypedContractMethod<
    [investor: AddressLike],
    [[bigint, bigint] & { pendingAmount: bigint; pendingCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTerms"
  ): TypedContractMethod<
    [],
    [BrazilianDebenture.DebentureTermsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVNARecord"
  ): TypedContractMethod<
    [],
    [BrazilianDebenture.VNARecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastDIUpdateDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mature"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "messageForTransferRestriction"
  ): TypedContractMethod<[code: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextCouponIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payCoupon"
  ): TypedContractMethod<[couponIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordCouponCalculation"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromBlacklist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmortizationSchedule"
  ): TypedContractMethod<
    [dates: BigNumberish[], percentages: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "terms"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean,
        string
      ] & {
        vne: bigint;
        totalSupplyUnits: bigint;
        issueDate: bigint;
        maturityDate: bigint;
        anniversaryDay: bigint;
        lockUpEndDate: bigint;
        rateType: bigint;
        fixedRate: bigint;
        percentDI: bigint;
        couponFrequencyDays: bigint;
        amortType: bigint;
        isinCode: string;
        cetipCode: string;
        series: string;
        hasRepactuacao: boolean;
        hasEarlyRedemption: boolean;
        comboId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDIFactor"
  ): TypedContractMethod<[diRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVNA"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vnaRecord"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        value: bigint;
        lastUpdateDate: bigint;
        lastIndexValue: bigint;
        accumulatedFactor: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "AmortizationPaid"
  ): TypedContractEvent<
    AmortizationPaidEvent.InputTuple,
    AmortizationPaidEvent.OutputTuple,
    AmortizationPaidEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BlacklistUpdated"
  ): TypedContractEvent<
    BlacklistUpdatedEvent.InputTuple,
    BlacklistUpdatedEvent.OutputTuple,
    BlacklistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CouponCalculated"
  ): TypedContractEvent<
    CouponCalculatedEvent.InputTuple,
    CouponCalculatedEvent.OutputTuple,
    CouponCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "CouponClaimed"
  ): TypedContractEvent<
    CouponClaimedEvent.InputTuple,
    CouponClaimedEvent.OutputTuple,
    CouponClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CouponPaid"
  ): TypedContractEvent<
    CouponPaidEvent.InputTuple,
    CouponPaidEvent.OutputTuple,
    CouponPaidEvent.OutputObject
  >;
  getEvent(
    key: "DebentureIssued"
  ): TypedContractEvent<
    DebentureIssuedEvent.InputTuple,
    DebentureIssuedEvent.OutputTuple,
    DebentureIssuedEvent.OutputObject
  >;
  getEvent(
    key: "EarlyRedemptionExecuted"
  ): TypedContractEvent<
    EarlyRedemptionExecutedEvent.InputTuple,
    EarlyRedemptionExecutedEvent.OutputTuple,
    EarlyRedemptionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RepactuationExecuted"
  ): TypedContractEvent<
    RepactuationExecutedEvent.InputTuple,
    RepactuationExecutedEvent.OutputTuple,
    RepactuationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StatusChanged"
  ): TypedContractEvent<
    StatusChangedEvent.InputTuple,
    StatusChangedEvent.OutputTuple,
    StatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VNAUpdated"
  ): TypedContractEvent<
    VNAUpdatedEvent.InputTuple,
    VNAUpdatedEvent.OutputTuple,
    VNAUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "AmortizationPaid(uint256,uint256,uint256)": TypedContractEvent<
      AmortizationPaidEvent.InputTuple,
      AmortizationPaidEvent.OutputTuple,
      AmortizationPaidEvent.OutputObject
    >;
    AmortizationPaid: TypedContractEvent<
      AmortizationPaidEvent.InputTuple,
      AmortizationPaidEvent.OutputTuple,
      AmortizationPaidEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BlacklistUpdated(address,bool)": TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;
    BlacklistUpdated: TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;

    "CouponCalculated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      CouponCalculatedEvent.InputTuple,
      CouponCalculatedEvent.OutputTuple,
      CouponCalculatedEvent.OutputObject
    >;
    CouponCalculated: TypedContractEvent<
      CouponCalculatedEvent.InputTuple,
      CouponCalculatedEvent.OutputTuple,
      CouponCalculatedEvent.OutputObject
    >;

    "CouponClaimed(address,uint256,uint256)": TypedContractEvent<
      CouponClaimedEvent.InputTuple,
      CouponClaimedEvent.OutputTuple,
      CouponClaimedEvent.OutputObject
    >;
    CouponClaimed: TypedContractEvent<
      CouponClaimedEvent.InputTuple,
      CouponClaimedEvent.OutputTuple,
      CouponClaimedEvent.OutputObject
    >;

    "CouponPaid(uint256,uint256,uint256)": TypedContractEvent<
      CouponPaidEvent.InputTuple,
      CouponPaidEvent.OutputTuple,
      CouponPaidEvent.OutputObject
    >;
    CouponPaid: TypedContractEvent<
      CouponPaidEvent.InputTuple,
      CouponPaidEvent.OutputTuple,
      CouponPaidEvent.OutputObject
    >;

    "DebentureIssued(string,uint256,uint256,uint8)": TypedContractEvent<
      DebentureIssuedEvent.InputTuple,
      DebentureIssuedEvent.OutputTuple,
      DebentureIssuedEvent.OutputObject
    >;
    DebentureIssued: TypedContractEvent<
      DebentureIssuedEvent.InputTuple,
      DebentureIssuedEvent.OutputTuple,
      DebentureIssuedEvent.OutputObject
    >;

    "EarlyRedemptionExecuted(uint256,uint256)": TypedContractEvent<
      EarlyRedemptionExecutedEvent.InputTuple,
      EarlyRedemptionExecutedEvent.OutputTuple,
      EarlyRedemptionExecutedEvent.OutputObject
    >;
    EarlyRedemptionExecuted: TypedContractEvent<
      EarlyRedemptionExecutedEvent.InputTuple,
      EarlyRedemptionExecutedEvent.OutputTuple,
      EarlyRedemptionExecutedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RepactuationExecuted(uint256,uint256)": TypedContractEvent<
      RepactuationExecutedEvent.InputTuple,
      RepactuationExecutedEvent.OutputTuple,
      RepactuationExecutedEvent.OutputObject
    >;
    RepactuationExecuted: TypedContractEvent<
      RepactuationExecutedEvent.InputTuple,
      RepactuationExecutedEvent.OutputTuple,
      RepactuationExecutedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StatusChanged(uint8,uint8,uint256)": TypedContractEvent<
      StatusChangedEvent.InputTuple,
      StatusChangedEvent.OutputTuple,
      StatusChangedEvent.OutputObject
    >;
    StatusChanged: TypedContractEvent<
      StatusChangedEvent.InputTuple,
      StatusChangedEvent.OutputTuple,
      StatusChangedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VNAUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      VNAUpdatedEvent.InputTuple,
      VNAUpdatedEvent.OutputTuple,
      VNAUpdatedEvent.OutputObject
    >;
    VNAUpdated: TypedContractEvent<
      VNAUpdatedEvent.InputTuple,
      VNAUpdatedEvent.OutputTuple,
      VNAUpdatedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
