/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBrazilianMacroOracleInterface extends Interface {
  getFunction(nameOrSignature: "getRate" | "getRateMetadata"): FunctionFragment;

  encodeFunctionData(functionFragment: "getRate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRateMetadata",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRateMetadata",
    data: BytesLike
  ): Result;
}

export interface IBrazilianMacroOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IBrazilianMacroOracle;
  waitForDeployment(): Promise<this>;

  interface: IBrazilianMacroOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRate: TypedContractMethod<
    [rateType: string],
    [
      [bigint, bigint, bigint] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
      }
    ],
    "view"
  >;

  getRateMetadata: TypedContractMethod<
    [rateType: string],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        description: string;
        decimals: bigint;
        heartbeat: bigint;
        minAnswer: bigint;
        maxAnswer: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRate"
  ): TypedContractMethod<
    [rateType: string],
    [
      [bigint, bigint, bigint] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRateMetadata"
  ): TypedContractMethod<
    [rateType: string],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        description: string;
        decimals: bigint;
        heartbeat: bigint;
        minAnswer: bigint;
        maxAnswer: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
