/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBrazilianMacroOracleClone,
  IBrazilianMacroOracleCloneInterface,
} from "../../../contracts/BrazilianDebentureCloneable.sol/IBrazilianMacroOracleClone";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "rateType",
        type: "string",
      },
    ],
    name: "getRate",
    outputs: [
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "realWorldDate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBrazilianMacroOracleClone__factory {
  static readonly abi = _abi;
  static createInterface(): IBrazilianMacroOracleCloneInterface {
    return new Interface(_abi) as IBrazilianMacroOracleCloneInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBrazilianMacroOracleClone {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBrazilianMacroOracleClone;
  }
}
