/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BrazilianMacroOracle {
  export type RateDataStruct = {
    answer: BigNumberish;
    timestamp: BigNumberish;
    realWorldDate: BigNumberish;
    source: string;
    updater: AddressLike;
  };

  export type RateDataStructOutput = [
    answer: bigint,
    timestamp: bigint,
    realWorldDate: bigint,
    source: string,
    updater: string
  ] & {
    answer: bigint;
    timestamp: bigint;
    realWorldDate: bigint;
    source: string;
    updater: string;
  };

  export type RateMetadataStruct = {
    name: string;
    description: string;
    decimals: BigNumberish;
    heartbeat: BigNumberish;
    minAnswer: BigNumberish;
    maxAnswer: BigNumberish;
    isActive: boolean;
  };

  export type RateMetadataStructOutput = [
    name: string,
    description: string,
    decimals: bigint,
    heartbeat: bigint,
    minAnswer: bigint,
    maxAnswer: bigint,
    isActive: boolean
  ] & {
    name: string;
    description: string;
    decimals: bigint;
    heartbeat: bigint;
    minAnswer: bigint;
    maxAnswer: bigint;
    isActive: boolean;
  };
}

export interface BrazilianMacroOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CHAINLINK_DECIMALS"
      | "DEFAULT_ADMIN_ROLE"
      | "PRECISION"
      | "UPDATER_ROLE"
      | "addRate"
      | "answerToPercentage"
      | "batchUpdateRates"
      | "currentRates"
      | "deactivateRate"
      | "decimals"
      | "description"
      | "getRate"
      | "getRateFull"
      | "getRateHistory"
      | "getRateMetadata"
      | "getRoleAdmin"
      | "getSupportedRates"
      | "getSupportedRatesCount"
      | "grantRole"
      | "hasRole"
      | "isRateStale"
      | "latestRoundData"
      | "pause"
      | "paused"
      | "rateExists"
      | "rateHistory"
      | "rateMetadata"
      | "reactivateRate"
      | "renounceRole"
      | "revokeRole"
      | "roundIds"
      | "supportedRates"
      | "supportsInterface"
      | "unpause"
      | "updateBounds"
      | "updateRate"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Paused"
      | "RateAdded"
      | "RateDeactivated"
      | "RateReactivated"
      | "RateUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHAINLINK_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UPDATER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRate",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "answerToPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateRates",
    values: [string[], BigNumberish[], BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateRate",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values: [string]): string;
  encodeFunctionData(functionFragment: "description", values: [string]): string;
  encodeFunctionData(functionFragment: "getRate", values: [string]): string;
  encodeFunctionData(functionFragment: "getRateFull", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRateHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRateMetadata",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedRates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedRatesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isRateStale", values: [string]): string;
  encodeFunctionData(
    functionFragment: "latestRoundData",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "rateExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "rateHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rateMetadata",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateRate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "roundIds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportedRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateBounds",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRate",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CHAINLINK_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPDATER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "answerToPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRateFull",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRateHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRateMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedRatesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRateStale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rateExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rateHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roundIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateAddedEvent {
  export type InputTuple = [
    rateType: string,
    name: string,
    decimals: BigNumberish,
    heartbeat: BigNumberish
  ];
  export type OutputTuple = [
    rateType: string,
    name: string,
    decimals: bigint,
    heartbeat: bigint
  ];
  export interface OutputObject {
    rateType: string;
    name: string;
    decimals: bigint;
    heartbeat: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateDeactivatedEvent {
  export type InputTuple = [rateType: string];
  export type OutputTuple = [rateType: string];
  export interface OutputObject {
    rateType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateReactivatedEvent {
  export type InputTuple = [rateType: string];
  export type OutputTuple = [rateType: string];
  export interface OutputObject {
    rateType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateUpdatedEvent {
  export type InputTuple = [
    rateType: string,
    answer: BigNumberish,
    realWorldDate: BigNumberish,
    source: string,
    updater: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    rateType: string,
    answer: bigint,
    realWorldDate: bigint,
    source: string,
    updater: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    rateType: string;
    answer: bigint;
    realWorldDate: bigint;
    source: string;
    updater: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BrazilianMacroOracle extends BaseContract {
  connect(runner?: ContractRunner | null): BrazilianMacroOracle;
  waitForDeployment(): Promise<this>;

  interface: BrazilianMacroOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CHAINLINK_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  UPDATER_ROLE: TypedContractMethod<[], [string], "view">;

  addRate: TypedContractMethod<
    [
      rateType: string,
      name: string,
      description: string,
      decimals: BigNumberish,
      heartbeat: BigNumberish,
      minAnswer: BigNumberish,
      maxAnswer: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  answerToPercentage: TypedContractMethod<
    [answer: BigNumberish],
    [[bigint, bigint] & { whole: bigint; fractional: bigint }],
    "view"
  >;

  batchUpdateRates: TypedContractMethod<
    [
      rateTypes: string[],
      answers: BigNumberish[],
      realWorldDates: BigNumberish[],
      sources: string[]
    ],
    [bigint],
    "nonpayable"
  >;

  currentRates: TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, bigint, string, string] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
        source: string;
        updater: string;
      }
    ],
    "view"
  >;

  deactivateRate: TypedContractMethod<[rateType: string], [void], "nonpayable">;

  decimals: TypedContractMethod<[rateType: string], [bigint], "view">;

  description: TypedContractMethod<[rateType: string], [string], "view">;

  getRate: TypedContractMethod<
    [rateType: string],
    [
      [bigint, bigint, bigint] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
      }
    ],
    "view"
  >;

  getRateFull: TypedContractMethod<
    [rateType: string],
    [BrazilianMacroOracle.RateDataStructOutput],
    "view"
  >;

  getRateHistory: TypedContractMethod<
    [rateType: string, count: BigNumberish],
    [BrazilianMacroOracle.RateDataStructOutput[]],
    "view"
  >;

  getRateMetadata: TypedContractMethod<
    [rateType: string],
    [BrazilianMacroOracle.RateMetadataStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSupportedRates: TypedContractMethod<[], [string[]], "view">;

  getSupportedRatesCount: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isRateStale: TypedContractMethod<[rateType: string], [boolean], "view">;

  latestRoundData: TypedContractMethod<
    [rateType: string],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  rateExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  rateHistory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, string] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
        source: string;
        updater: string;
      }
    ],
    "view"
  >;

  rateMetadata: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        description: string;
        decimals: bigint;
        heartbeat: bigint;
        minAnswer: bigint;
        maxAnswer: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  reactivateRate: TypedContractMethod<[rateType: string], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  roundIds: TypedContractMethod<[arg0: string], [bigint], "view">;

  supportedRates: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateBounds: TypedContractMethod<
    [rateType: string, minAnswer: BigNumberish, maxAnswer: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRate: TypedContractMethod<
    [
      rateType: string,
      answer: BigNumberish,
      realWorldDate: BigNumberish,
      source: string
    ],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CHAINLINK_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPDATER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRate"
  ): TypedContractMethod<
    [
      rateType: string,
      name: string,
      description: string,
      decimals: BigNumberish,
      heartbeat: BigNumberish,
      minAnswer: BigNumberish,
      maxAnswer: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "answerToPercentage"
  ): TypedContractMethod<
    [answer: BigNumberish],
    [[bigint, bigint] & { whole: bigint; fractional: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchUpdateRates"
  ): TypedContractMethod<
    [
      rateTypes: string[],
      answers: BigNumberish[],
      realWorldDates: BigNumberish[],
      sources: string[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentRates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, bigint, string, string] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
        source: string;
        updater: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateRate"
  ): TypedContractMethod<[rateType: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[rateType: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[rateType: string], [string], "view">;
  getFunction(
    nameOrSignature: "getRate"
  ): TypedContractMethod<
    [rateType: string],
    [
      [bigint, bigint, bigint] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRateFull"
  ): TypedContractMethod<
    [rateType: string],
    [BrazilianMacroOracle.RateDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRateHistory"
  ): TypedContractMethod<
    [rateType: string, count: BigNumberish],
    [BrazilianMacroOracle.RateDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRateMetadata"
  ): TypedContractMethod<
    [rateType: string],
    [BrazilianMacroOracle.RateMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSupportedRates"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSupportedRatesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRateStale"
  ): TypedContractMethod<[rateType: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "latestRoundData"
  ): TypedContractMethod<
    [rateType: string],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        answer: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rateExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "rateHistory"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, string] & {
        answer: bigint;
        timestamp: bigint;
        realWorldDate: bigint;
        source: string;
        updater: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rateMetadata"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        description: string;
        decimals: bigint;
        heartbeat: bigint;
        minAnswer: bigint;
        maxAnswer: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateRate"
  ): TypedContractMethod<[rateType: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roundIds"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportedRates"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBounds"
  ): TypedContractMethod<
    [rateType: string, minAnswer: BigNumberish, maxAnswer: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRate"
  ): TypedContractMethod<
    [
      rateType: string,
      answer: BigNumberish,
      realWorldDate: BigNumberish,
      source: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RateAdded"
  ): TypedContractEvent<
    RateAddedEvent.InputTuple,
    RateAddedEvent.OutputTuple,
    RateAddedEvent.OutputObject
  >;
  getEvent(
    key: "RateDeactivated"
  ): TypedContractEvent<
    RateDeactivatedEvent.InputTuple,
    RateDeactivatedEvent.OutputTuple,
    RateDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "RateReactivated"
  ): TypedContractEvent<
    RateReactivatedEvent.InputTuple,
    RateReactivatedEvent.OutputTuple,
    RateReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "RateUpdated"
  ): TypedContractEvent<
    RateUpdatedEvent.InputTuple,
    RateUpdatedEvent.OutputTuple,
    RateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RateAdded(string,string,uint8,uint256)": TypedContractEvent<
      RateAddedEvent.InputTuple,
      RateAddedEvent.OutputTuple,
      RateAddedEvent.OutputObject
    >;
    RateAdded: TypedContractEvent<
      RateAddedEvent.InputTuple,
      RateAddedEvent.OutputTuple,
      RateAddedEvent.OutputObject
    >;

    "RateDeactivated(string)": TypedContractEvent<
      RateDeactivatedEvent.InputTuple,
      RateDeactivatedEvent.OutputTuple,
      RateDeactivatedEvent.OutputObject
    >;
    RateDeactivated: TypedContractEvent<
      RateDeactivatedEvent.InputTuple,
      RateDeactivatedEvent.OutputTuple,
      RateDeactivatedEvent.OutputObject
    >;

    "RateReactivated(string)": TypedContractEvent<
      RateReactivatedEvent.InputTuple,
      RateReactivatedEvent.OutputTuple,
      RateReactivatedEvent.OutputObject
    >;
    RateReactivated: TypedContractEvent<
      RateReactivatedEvent.InputTuple,
      RateReactivatedEvent.OutputTuple,
      RateReactivatedEvent.OutputObject
    >;

    "RateUpdated(string,int256,uint256,string,address,uint256)": TypedContractEvent<
      RateUpdatedEvent.InputTuple,
      RateUpdatedEvent.OutputTuple,
      RateUpdatedEvent.OutputObject
    >;
    RateUpdated: TypedContractEvent<
      RateUpdatedEvent.InputTuple,
      RateUpdatedEvent.OutputTuple,
      RateUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
