/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BrazilianDebenture {
  export type DebentureTermsStruct = {
    vne: BigNumberish;
    totalSupplyUnits: BigNumberish;
    issueDate: BigNumberish;
    maturityDate: BigNumberish;
    anniversaryDay: BigNumberish;
    lockUpEndDate: BigNumberish;
    rateType: BigNumberish;
    fixedRate: BigNumberish;
    percentDI: BigNumberish;
    couponFrequencyDays: BigNumberish;
    amortType: BigNumberish;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: BytesLike;
  };

  export type DebentureTermsStructOutput = [
    vne: bigint,
    totalSupplyUnits: bigint,
    issueDate: bigint,
    maturityDate: bigint,
    anniversaryDay: bigint,
    lockUpEndDate: bigint,
    rateType: bigint,
    fixedRate: bigint,
    percentDI: bigint,
    couponFrequencyDays: bigint,
    amortType: bigint,
    isinCode: string,
    cetipCode: string,
    series: string,
    hasRepactuacao: boolean,
    hasEarlyRedemption: boolean,
    comboId: string
  ] & {
    vne: bigint;
    totalSupplyUnits: bigint;
    issueDate: bigint;
    maturityDate: bigint;
    anniversaryDay: bigint;
    lockUpEndDate: bigint;
    rateType: bigint;
    fixedRate: bigint;
    percentDI: bigint;
    couponFrequencyDays: bigint;
    amortType: bigint;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: string;
  };
}

export declare namespace DebentureFactory {
  export type DebentureTemplateStruct = {
    name: string;
    description: string;
    couponFrequencyDays: BigNumberish;
    amortType: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type DebentureTemplateStructOutput = [
    name: string,
    description: string,
    couponFrequencyDays: bigint,
    amortType: bigint,
    isActive: boolean,
    createdAt: bigint
  ] & {
    name: string;
    description: string;
    couponFrequencyDays: bigint;
    amortType: bigint;
    isActive: boolean;
    createdAt: bigint;
  };
}

export interface DebentureFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allDebentures"
      | "createDebenture"
      | "createDebentureFromTemplate"
      | "deactivateTemplate"
      | "debenturesByISIN"
      | "defaultPaymentToken"
      | "getAllTemplateIds"
      | "getDebentureAtIndex"
      | "getDebentureByISIN"
      | "getDebentureCount"
      | "getIssuerDebentures"
      | "getTemplate"
      | "getTemplateCount"
      | "issuerDebentures"
      | "oracle"
      | "owner"
      | "reactivateTemplate"
      | "renounceOwnership"
      | "setDefaultPaymentToken"
      | "setOracle"
      | "templateIds"
      | "templates"
      | "transferOwnership"
      | "upsertTemplate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebentureCreated"
      | "OwnershipTransferred"
      | "TemplateDeleted"
      | "TemplateUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allDebentures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDebenture",
    values: [
      string,
      string,
      BrazilianDebenture.DebentureTermsStruct,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createDebentureFromTemplate",
    values: [
      string,
      string,
      string,
      BrazilianDebenture.DebentureTermsStruct,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateTemplate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "debenturesByISIN",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPaymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTemplateIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDebentureAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebentureByISIN",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebentureCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerDebentures",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getTemplate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTemplateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerDebentures",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateTemplate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "templateIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "templates", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upsertTemplate",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDebenture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDebentureFromTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debenturesByISIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTemplateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebentureAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebentureByISIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebentureCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "templateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "templates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upsertTemplate",
    data: BytesLike
  ): Result;
}

export namespace DebentureCreatedEvent {
  export type InputTuple = [
    debentureAddress: AddressLike,
    isinCode: string,
    name: string,
    symbol: string,
    issuer: AddressLike,
    vne: BigNumberish,
    totalSupply: BigNumberish
  ];
  export type OutputTuple = [
    debentureAddress: string,
    isinCode: string,
    name: string,
    symbol: string,
    issuer: string,
    vne: bigint,
    totalSupply: bigint
  ];
  export interface OutputObject {
    debentureAddress: string;
    isinCode: string;
    name: string;
    symbol: string;
    issuer: string;
    vne: bigint;
    totalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TemplateDeletedEvent {
  export type InputTuple = [templateId: string];
  export type OutputTuple = [templateId: string];
  export interface OutputObject {
    templateId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TemplateUpdatedEvent {
  export type InputTuple = [
    templateId: string,
    couponFrequencyDays: BigNumberish,
    amortType: BigNumberish
  ];
  export type OutputTuple = [
    templateId: string,
    couponFrequencyDays: bigint,
    amortType: bigint
  ];
  export interface OutputObject {
    templateId: string;
    couponFrequencyDays: bigint;
    amortType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DebentureFactory extends BaseContract {
  connect(runner?: ContractRunner | null): DebentureFactory;
  waitForDeployment(): Promise<this>;

  interface: DebentureFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allDebentures: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createDebenture: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _terms: BrazilianDebenture.DebentureTermsStruct,
      _paymentToken: AddressLike,
      _trustee: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  createDebentureFromTemplate: TypedContractMethod<
    [
      _templateId: string,
      _name: string,
      _symbol: string,
      _terms: BrazilianDebenture.DebentureTermsStruct,
      _paymentToken: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  deactivateTemplate: TypedContractMethod<
    [_templateId: string],
    [void],
    "nonpayable"
  >;

  debenturesByISIN: TypedContractMethod<[arg0: string], [string], "view">;

  defaultPaymentToken: TypedContractMethod<[], [string], "view">;

  getAllTemplateIds: TypedContractMethod<[], [string[]], "view">;

  getDebentureAtIndex: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getDebentureByISIN: TypedContractMethod<
    [_isinCode: string],
    [string],
    "view"
  >;

  getDebentureCount: TypedContractMethod<[], [bigint], "view">;

  getIssuerDebentures: TypedContractMethod<
    [_issuer: AddressLike],
    [string[]],
    "view"
  >;

  getTemplate: TypedContractMethod<
    [_templateId: string],
    [DebentureFactory.DebentureTemplateStructOutput],
    "view"
  >;

  getTemplateCount: TypedContractMethod<[], [bigint], "view">;

  issuerDebentures: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  reactivateTemplate: TypedContractMethod<
    [_templateId: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDefaultPaymentToken: TypedContractMethod<
    [_newPaymentToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [_newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  templateIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  templates: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        name: string;
        description: string;
        couponFrequencyDays: bigint;
        amortType: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upsertTemplate: TypedContractMethod<
    [
      _templateId: string,
      _name: string,
      _description: string,
      _couponFrequencyDays: BigNumberish,
      _amortType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allDebentures"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createDebenture"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _terms: BrazilianDebenture.DebentureTermsStruct,
      _paymentToken: AddressLike,
      _trustee: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDebentureFromTemplate"
  ): TypedContractMethod<
    [
      _templateId: string,
      _name: string,
      _symbol: string,
      _terms: BrazilianDebenture.DebentureTermsStruct,
      _paymentToken: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateTemplate"
  ): TypedContractMethod<[_templateId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "debenturesByISIN"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "defaultPaymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllTemplateIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDebentureAtIndex"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDebentureByISIN"
  ): TypedContractMethod<[_isinCode: string], [string], "view">;
  getFunction(
    nameOrSignature: "getDebentureCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getIssuerDebentures"
  ): TypedContractMethod<[_issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTemplate"
  ): TypedContractMethod<
    [_templateId: string],
    [DebentureFactory.DebentureTemplateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTemplateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "issuerDebentures"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateTemplate"
  ): TypedContractMethod<[_templateId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultPaymentToken"
  ): TypedContractMethod<[_newPaymentToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[_newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "templateIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "templates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        name: string;
        description: string;
        couponFrequencyDays: bigint;
        amortType: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upsertTemplate"
  ): TypedContractMethod<
    [
      _templateId: string,
      _name: string,
      _description: string,
      _couponFrequencyDays: BigNumberish,
      _amortType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DebentureCreated"
  ): TypedContractEvent<
    DebentureCreatedEvent.InputTuple,
    DebentureCreatedEvent.OutputTuple,
    DebentureCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TemplateDeleted"
  ): TypedContractEvent<
    TemplateDeletedEvent.InputTuple,
    TemplateDeletedEvent.OutputTuple,
    TemplateDeletedEvent.OutputObject
  >;
  getEvent(
    key: "TemplateUpdated"
  ): TypedContractEvent<
    TemplateUpdatedEvent.InputTuple,
    TemplateUpdatedEvent.OutputTuple,
    TemplateUpdatedEvent.OutputObject
  >;

  filters: {
    "DebentureCreated(address,string,string,string,address,uint256,uint256)": TypedContractEvent<
      DebentureCreatedEvent.InputTuple,
      DebentureCreatedEvent.OutputTuple,
      DebentureCreatedEvent.OutputObject
    >;
    DebentureCreated: TypedContractEvent<
      DebentureCreatedEvent.InputTuple,
      DebentureCreatedEvent.OutputTuple,
      DebentureCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TemplateDeleted(string)": TypedContractEvent<
      TemplateDeletedEvent.InputTuple,
      TemplateDeletedEvent.OutputTuple,
      TemplateDeletedEvent.OutputObject
    >;
    TemplateDeleted: TypedContractEvent<
      TemplateDeletedEvent.InputTuple,
      TemplateDeletedEvent.OutputTuple,
      TemplateDeletedEvent.OutputObject
    >;

    "TemplateUpdated(string,uint256,uint8)": TypedContractEvent<
      TemplateUpdatedEvent.InputTuple,
      TemplateUpdatedEvent.OutputTuple,
      TemplateUpdatedEvent.OutputObject
    >;
    TemplateUpdated: TypedContractEvent<
      TemplateUpdatedEvent.InputTuple,
      TemplateUpdatedEvent.OutputTuple,
      TemplateUpdatedEvent.OutputObject
    >;
  };
}
