/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BrazilianDebentureCloneable {
  export type DebentureTermsStruct = {
    vne: BigNumberish;
    totalSupplyUnits: BigNumberish;
    issueDate: BigNumberish;
    maturityDate: BigNumberish;
    anniversaryDay: BigNumberish;
    lockUpEndDate: BigNumberish;
    rateType: BigNumberish;
    fixedRate: BigNumberish;
    percentDI: BigNumberish;
    couponFrequencyDays: BigNumberish;
    amortType: BigNumberish;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: BytesLike;
  };

  export type DebentureTermsStructOutput = [
    vne: bigint,
    totalSupplyUnits: bigint,
    issueDate: bigint,
    maturityDate: bigint,
    anniversaryDay: bigint,
    lockUpEndDate: bigint,
    rateType: bigint,
    fixedRate: bigint,
    percentDI: bigint,
    couponFrequencyDays: bigint,
    amortType: bigint,
    isinCode: string,
    cetipCode: string,
    series: string,
    hasRepactuacao: boolean,
    hasEarlyRedemption: boolean,
    comboId: string
  ] & {
    vne: bigint;
    totalSupplyUnits: bigint;
    issueDate: bigint;
    maturityDate: bigint;
    anniversaryDay: bigint;
    lockUpEndDate: bigint;
    rateType: bigint;
    fixedRate: bigint;
    percentDI: bigint;
    couponFrequencyDays: bigint;
    amortType: bigint;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: string;
  };
}

export interface DebentureCloneFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allDebentures"
      | "authorizedIssuers"
      | "batchAuthorizeIssuers"
      | "createDebenture"
      | "createDeterministicDebenture"
      | "debenturesByISIN"
      | "defaultPaymentToken"
      | "getAllDebentures"
      | "getDebentureInfo"
      | "getIssuerDebentures"
      | "getTotalDebentures"
      | "implementation"
      | "isinExists"
      | "issuerDebentures"
      | "oracle"
      | "owner"
      | "predictDeterministicAddress"
      | "renounceOwnership"
      | "setAuthorizedIssuer"
      | "setDefaultPaymentToken"
      | "setOracle"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebentureCreated"
      | "DefaultPaymentTokenUpdated"
      | "IssuerAuthorized"
      | "OracleUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allDebentures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAuthorizeIssuers",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createDebenture",
    values: [
      string,
      string,
      BrazilianDebentureCloneable.DebentureTermsStruct,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createDeterministicDebenture",
    values: [
      string,
      string,
      BrazilianDebentureCloneable.DebentureTermsStruct,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "debenturesByISIN",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPaymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDebentures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDebentureInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerDebentures",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDebentures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isinExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "issuerDebentures",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictDeterministicAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedIssuer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAuthorizeIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDebenture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDeterministicDebenture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debenturesByISIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebentureInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isinExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuerDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictDeterministicAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DebentureCreatedEvent {
  export type InputTuple = [
    debentureAddress: AddressLike,
    isinCode: string,
    name: string,
    symbol: string,
    issuer: AddressLike,
    vne: BigNumberish,
    totalSupply: BigNumberish
  ];
  export type OutputTuple = [
    debentureAddress: string,
    isinCode: string,
    name: string,
    symbol: string,
    issuer: string,
    vne: bigint,
    totalSupply: bigint
  ];
  export interface OutputObject {
    debentureAddress: string;
    isinCode: string;
    name: string;
    symbol: string;
    issuer: string;
    vne: bigint;
    totalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultPaymentTokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizedEvent {
  export type InputTuple = [issuer: AddressLike, authorized: boolean];
  export type OutputTuple = [issuer: string, authorized: boolean];
  export interface OutputObject {
    issuer: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
  export type OutputTuple = [oldOracle: string, newOracle: string];
  export interface OutputObject {
    oldOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DebentureCloneFactory extends BaseContract {
  connect(runner?: ContractRunner | null): DebentureCloneFactory;
  waitForDeployment(): Promise<this>;

  interface: DebentureCloneFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allDebentures: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  authorizedIssuers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchAuthorizeIssuers: TypedContractMethod<
    [issuers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  createDebenture: TypedContractMethod<
    [
      name: string,
      symbol: string,
      terms: BrazilianDebentureCloneable.DebentureTermsStruct,
      paymentToken: AddressLike,
      trustee: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  createDeterministicDebenture: TypedContractMethod<
    [
      name: string,
      symbol: string,
      terms: BrazilianDebentureCloneable.DebentureTermsStruct,
      paymentToken: AddressLike,
      trustee: AddressLike,
      salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  debenturesByISIN: TypedContractMethod<[arg0: string], [string], "view">;

  defaultPaymentToken: TypedContractMethod<[], [string], "view">;

  getAllDebentures: TypedContractMethod<[], [string[]], "view">;

  getDebentureInfo: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, string, string, bigint, bigint] & {
        debentureAddress: string;
        name: string;
        symbol: string;
        isinCode: string;
        vne: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getIssuerDebentures: TypedContractMethod<
    [issuer: AddressLike],
    [string[]],
    "view"
  >;

  getTotalDebentures: TypedContractMethod<[], [bigint], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  isinExists: TypedContractMethod<[isinCode: string], [boolean], "view">;

  issuerDebentures: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  predictDeterministicAddress: TypedContractMethod<
    [salt: BytesLike],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedIssuer: TypedContractMethod<
    [issuer: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setDefaultPaymentToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allDebentures"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchAuthorizeIssuers"
  ): TypedContractMethod<[issuers: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDebenture"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      terms: BrazilianDebentureCloneable.DebentureTermsStruct,
      paymentToken: AddressLike,
      trustee: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDeterministicDebenture"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      terms: BrazilianDebentureCloneable.DebentureTermsStruct,
      paymentToken: AddressLike,
      trustee: AddressLike,
      salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "debenturesByISIN"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "defaultPaymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllDebentures"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDebentureInfo"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, string, string, bigint, bigint] & {
        debentureAddress: string;
        name: string;
        symbol: string;
        isinCode: string;
        vne: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIssuerDebentures"
  ): TypedContractMethod<[issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalDebentures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isinExists"
  ): TypedContractMethod<[isinCode: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuerDebentures"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictDeterministicAddress"
  ): TypedContractMethod<[salt: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedIssuer"
  ): TypedContractMethod<
    [issuer: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultPaymentToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DebentureCreated"
  ): TypedContractEvent<
    DebentureCreatedEvent.InputTuple,
    DebentureCreatedEvent.OutputTuple,
    DebentureCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultPaymentTokenUpdated"
  ): TypedContractEvent<
    DefaultPaymentTokenUpdatedEvent.InputTuple,
    DefaultPaymentTokenUpdatedEvent.OutputTuple,
    DefaultPaymentTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorized"
  ): TypedContractEvent<
    IssuerAuthorizedEvent.InputTuple,
    IssuerAuthorizedEvent.OutputTuple,
    IssuerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DebentureCreated(address,string,string,string,address,uint256,uint256)": TypedContractEvent<
      DebentureCreatedEvent.InputTuple,
      DebentureCreatedEvent.OutputTuple,
      DebentureCreatedEvent.OutputObject
    >;
    DebentureCreated: TypedContractEvent<
      DebentureCreatedEvent.InputTuple,
      DebentureCreatedEvent.OutputTuple,
      DebentureCreatedEvent.OutputObject
    >;

    "DefaultPaymentTokenUpdated(address,address)": TypedContractEvent<
      DefaultPaymentTokenUpdatedEvent.InputTuple,
      DefaultPaymentTokenUpdatedEvent.OutputTuple,
      DefaultPaymentTokenUpdatedEvent.OutputObject
    >;
    DefaultPaymentTokenUpdated: TypedContractEvent<
      DefaultPaymentTokenUpdatedEvent.InputTuple,
      DefaultPaymentTokenUpdatedEvent.OutputTuple,
      DefaultPaymentTokenUpdatedEvent.OutputObject
    >;

    "IssuerAuthorized(address,bool)": TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
    IssuerAuthorized: TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;

    "OracleUpdated(address,address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
