/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as brazilianDebentureSol from "./BrazilianDebenture.sol";
export type { brazilianDebentureSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { BrazilianMacroOracle } from "./BrazilianMacroOracle";
export type { DebentureFactory } from "./DebentureFactory";
