/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleDebentureRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allDebentures"
      | "debenturesByISIN"
      | "getAllDebentures"
      | "getIssuerDebentures"
      | "getTotalDebentures"
      | "issuerDebentures"
      | "oracle"
      | "owner"
      | "registerDebenture"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DebentureRegistered" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allDebentures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debenturesByISIN",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDebentures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerDebentures",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDebentures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerDebentures",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDebenture",
    values: [AddressLike, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debenturesByISIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerDebentures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDebenture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DebentureRegisteredEvent {
  export type InputTuple = [
    debentureAddress: AddressLike,
    isinCode: string,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    debentureAddress: string,
    isinCode: string,
    issuer: string
  ];
  export interface OutputObject {
    debentureAddress: string;
    isinCode: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleDebentureRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleDebentureRegistry;
  waitForDeployment(): Promise<this>;

  interface: SimpleDebentureRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allDebentures: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  debenturesByISIN: TypedContractMethod<[arg0: string], [string], "view">;

  getAllDebentures: TypedContractMethod<[], [string[]], "view">;

  getIssuerDebentures: TypedContractMethod<
    [issuer: AddressLike],
    [string[]],
    "view"
  >;

  getTotalDebentures: TypedContractMethod<[], [bigint], "view">;

  issuerDebentures: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerDebenture: TypedContractMethod<
    [debentureAddress: AddressLike, isinCode: string, issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allDebentures"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "debenturesByISIN"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getAllDebentures"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getIssuerDebentures"
  ): TypedContractMethod<[issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalDebentures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "issuerDebentures"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDebenture"
  ): TypedContractMethod<
    [debentureAddress: AddressLike, isinCode: string, issuer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DebentureRegistered"
  ): TypedContractEvent<
    DebentureRegisteredEvent.InputTuple,
    DebentureRegisteredEvent.OutputTuple,
    DebentureRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DebentureRegistered(address,string,address)": TypedContractEvent<
      DebentureRegisteredEvent.InputTuple,
      DebentureRegisteredEvent.OutputTuple,
      DebentureRegisteredEvent.OutputObject
    >;
    DebentureRegistered: TypedContractEvent<
      DebentureRegisteredEvent.InputTuple,
      DebentureRegisteredEvent.OutputTuple,
      DebentureRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
