/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BrazilianDebentureCloneable {
  export type DebentureTermsStruct = {
    vne: BigNumberish;
    totalSupplyUnits: BigNumberish;
    issueDate: BigNumberish;
    maturityDate: BigNumberish;
    anniversaryDay: BigNumberish;
    lockUpEndDate: BigNumberish;
    rateType: BigNumberish;
    fixedRate: BigNumberish;
    percentDI: BigNumberish;
    couponFrequencyDays: BigNumberish;
    amortType: BigNumberish;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: BytesLike;
  };

  export type DebentureTermsStructOutput = [
    vne: bigint,
    totalSupplyUnits: bigint,
    issueDate: bigint,
    maturityDate: bigint,
    anniversaryDay: bigint,
    lockUpEndDate: bigint,
    rateType: bigint,
    fixedRate: bigint,
    percentDI: bigint,
    couponFrequencyDays: bigint,
    amortType: bigint,
    isinCode: string,
    cetipCode: string,
    series: string,
    hasRepactuacao: boolean,
    hasEarlyRedemption: boolean,
    comboId: string
  ] & {
    vne: bigint;
    totalSupplyUnits: bigint;
    issueDate: bigint;
    maturityDate: bigint;
    anniversaryDay: bigint;
    lockUpEndDate: bigint;
    rateType: bigint;
    fixedRate: bigint;
    percentDI: bigint;
    couponFrequencyDays: bigint;
    amortType: bigint;
    isinCode: string;
    cetipCode: string;
    series: string;
    hasRepactuacao: boolean;
    hasEarlyRedemption: boolean;
    comboId: string;
  };

  export type VNARecordStruct = {
    value: BigNumberish;
    lastUpdateDate: BigNumberish;
    lastIndexValue: BigNumberish;
    accumulatedFactor: BigNumberish;
  };

  export type VNARecordStructOutput = [
    value: bigint,
    lastUpdateDate: bigint,
    lastIndexValue: bigint,
    accumulatedFactor: bigint
  ] & {
    value: bigint;
    lastUpdateDate: bigint;
    lastIndexValue: bigint;
    accumulatedFactor: bigint;
  };

  export type AmortizationScheduleStruct = {
    date: BigNumberish;
    percentOrValue: BigNumberish;
    executed: boolean;
  };

  export type AmortizationScheduleStructOutput = [
    date: bigint,
    percentOrValue: bigint,
    executed: boolean
  ] & { date: bigint; percentOrValue: bigint; executed: boolean };
}

export interface BrazilianDebentureCloneableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "BLACKLISTED"
      | "BUSINESS_DAYS_YEAR"
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_ROLE"
      | "LOCK_UP_PERIOD"
      | "NOT_WHITELISTED"
      | "PAUSED"
      | "PRECISION_PERCENT_DI"
      | "PRECISION_PU"
      | "PRECISION_RATE"
      | "SUCCESS"
      | "TRUSTEE_ROLE"
      | "WHITELIST_ADMIN_ROLE"
      | "accumulatedDIFactor"
      | "addToBlacklist"
      | "addToWhitelist"
      | "allowance"
      | "amortizationSchedule"
      | "approve"
      | "balanceOf"
      | "batchAddToWhitelist"
      | "blacklist"
      | "claimAllCoupons"
      | "claimCoupon"
      | "couponClaimed"
      | "couponRecords"
      | "decimals"
      | "declareDefault"
      | "declareMaturity"
      | "depositPaymentTokens"
      | "detectTransferRestriction"
      | "earlyRedemption"
      | "executeAmortization"
      | "getAmortizationScheduleLength"
      | "getCouponCount"
      | "getPendingClaims"
      | "getRoleAdmin"
      | "getTerms"
      | "getVNA"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isInitialized"
      | "issuer"
      | "lastDIUpdateDate"
      | "messageForTransferRestriction"
      | "name"
      | "oracle"
      | "pause"
      | "paused"
      | "paymentToken"
      | "recordCoupon"
      | "removeFromBlacklist"
      | "removeFromWhitelist"
      | "renounceRole"
      | "revokeRole"
      | "setAmortizationSchedule"
      | "status"
      | "supportsInterface"
      | "symbol"
      | "terms"
      | "totalAmortized"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "trustee"
      | "unpause"
      | "vnaRecord"
      | "whitelist"
      | "withdrawPaymentTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmortizationExecuted"
      | "Approval"
      | "BlacklistUpdated"
      | "CouponClaimed"
      | "CouponRecorded"
      | "DebentureInitialized"
      | "Initialized"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StatusChanged"
      | "Transfer"
      | "Unpaused"
      | "VNAUpdated"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BLACKLISTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUSINESS_DAYS_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_UP_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NOT_WHITELISTED",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PAUSED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PRECISION_PERCENT_DI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISION_PU",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SUCCESS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TRUSTEE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WHITELIST_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedDIFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "amortizationSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddToWhitelist",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllCoupons",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimCoupon",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "couponClaimed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "couponRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "declareDefault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "declareMaturity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositPaymentTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "detectTransferRestriction",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyRedemption",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeAmortization",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmortizationScheduleLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCouponCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingClaims",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTerms", values?: undefined): string;
  encodeFunctionData(functionFragment: "getVNA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      BrazilianDebentureCloneable.DebentureTermsStruct,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "issuer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastDIUpdateDate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageForTransferRestriction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordCoupon",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAmortizationSchedule",
    values: [BrazilianDebentureCloneable.AmortizationScheduleStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "terms", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAmortized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "trustee", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "vnaRecord", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPaymentTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BLACKLISTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUSINESS_DAYS_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_UP_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NOT_WHITELISTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PAUSED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRECISION_PERCENT_DI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRECISION_PU",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRECISION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SUCCESS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TRUSTEE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WHITELIST_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedDIFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "amortizationSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchAddToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimAllCoupons",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCoupon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "couponClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "couponRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "declareDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declareMaturity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPaymentTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "detectTransferRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earlyRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAmortization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmortizationScheduleLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCouponCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTerms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVNA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastDIUpdateDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageForTransferRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCoupon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAmortizationSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "terms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAmortized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trustee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vnaRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPaymentTokens",
    data: BytesLike
  ): Result;
}

export namespace AmortizationExecutedEvent {
  export type InputTuple = [scheduleIndex: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [scheduleIndex: bigint, amount: bigint];
  export interface OutputObject {
    scheduleIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlacklistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouponClaimedEvent {
  export type InputTuple = [
    holder: AddressLike,
    couponIndex: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    holder: string,
    couponIndex: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    holder: string;
    couponIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouponRecordedEvent {
  export type InputTuple = [
    couponIndex: BigNumberish,
    puPerUnit: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    couponIndex: bigint,
    puPerUnit: bigint,
    totalAmount: bigint
  ];
  export interface OutputObject {
    couponIndex: bigint;
    puPerUnit: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebentureInitializedEvent {
  export type InputTuple = [
    isinCode: string,
    vne: BigNumberish,
    totalSupply: BigNumberish,
    rateType: BigNumberish
  ];
  export type OutputTuple = [
    isinCode: string,
    vne: bigint,
    totalSupply: bigint,
    rateType: bigint
  ];
  export interface OutputObject {
    isinCode: string;
    vne: bigint;
    totalSupply: bigint;
    rateType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedEvent {
  export type InputTuple = [oldStatus: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [oldStatus: bigint, newStatus: bigint];
  export interface OutputObject {
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VNAUpdatedEvent {
  export type InputTuple = [
    newValue: BigNumberish,
    indexValue: BigNumberish,
    factor: BigNumberish
  ];
  export type OutputTuple = [
    newValue: bigint,
    indexValue: bigint,
    factor: bigint
  ];
  export interface OutputObject {
    newValue: bigint;
    indexValue: bigint;
    factor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BrazilianDebentureCloneable extends BaseContract {
  connect(runner?: ContractRunner | null): BrazilianDebentureCloneable;
  waitForDeployment(): Promise<this>;

  interface: BrazilianDebentureCloneableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BLACKLISTED: TypedContractMethod<[], [bigint], "view">;

  BUSINESS_DAYS_YEAR: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_ROLE: TypedContractMethod<[], [string], "view">;

  LOCK_UP_PERIOD: TypedContractMethod<[], [bigint], "view">;

  NOT_WHITELISTED: TypedContractMethod<[], [bigint], "view">;

  PAUSED: TypedContractMethod<[], [bigint], "view">;

  PRECISION_PERCENT_DI: TypedContractMethod<[], [bigint], "view">;

  PRECISION_PU: TypedContractMethod<[], [bigint], "view">;

  PRECISION_RATE: TypedContractMethod<[], [bigint], "view">;

  SUCCESS: TypedContractMethod<[], [bigint], "view">;

  TRUSTEE_ROLE: TypedContractMethod<[], [string], "view">;

  WHITELIST_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  accumulatedDIFactor: TypedContractMethod<[], [bigint], "view">;

  addToBlacklist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  addToWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  amortizationSchedule: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        date: bigint;
        percentOrValue: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  batchAddToWhitelist: TypedContractMethod<
    [accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  blacklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  claimAllCoupons: TypedContractMethod<[], [void], "nonpayable">;

  claimCoupon: TypedContractMethod<
    [couponIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  couponClaimed: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  couponRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        date: bigint;
        puPerUnit: bigint;
        totalAmount: bigint;
        distributed: boolean;
      }
    ],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  declareDefault: TypedContractMethod<[], [void], "nonpayable">;

  declareMaturity: TypedContractMethod<[], [void], "nonpayable">;

  depositPaymentTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  detectTransferRestriction: TypedContractMethod<
    [from: AddressLike, to: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  earlyRedemption: TypedContractMethod<[], [void], "nonpayable">;

  executeAmortization: TypedContractMethod<
    [scheduleIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAmortizationScheduleLength: TypedContractMethod<[], [bigint], "view">;

  getCouponCount: TypedContractMethod<[], [bigint], "view">;

  getPendingClaims: TypedContractMethod<
    [holder: AddressLike],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTerms: TypedContractMethod<
    [],
    [BrazilianDebentureCloneable.DebentureTermsStructOutput],
    "view"
  >;

  getVNA: TypedContractMethod<
    [],
    [BrazilianDebentureCloneable.VNARecordStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      initName: string,
      initSymbol: string,
      initTerms: BrazilianDebentureCloneable.DebentureTermsStruct,
      initOracle: AddressLike,
      initPaymentToken: AddressLike,
      initIssuer: AddressLike,
      initTrustee: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  issuer: TypedContractMethod<[], [string], "view">;

  lastDIUpdateDate: TypedContractMethod<[], [bigint], "view">;

  messageForTransferRestriction: TypedContractMethod<
    [restrictionCode: BigNumberish],
    [string],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  recordCoupon: TypedContractMethod<
    [puPerUnit: BigNumberish, totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeFromBlacklist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  removeFromWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAmortizationSchedule: TypedContractMethod<
    [schedule: BrazilianDebentureCloneable.AmortizationScheduleStruct[]],
    [void],
    "nonpayable"
  >;

  status: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  terms: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean,
        string
      ] & {
        vne: bigint;
        totalSupplyUnits: bigint;
        issueDate: bigint;
        maturityDate: bigint;
        anniversaryDay: bigint;
        lockUpEndDate: bigint;
        rateType: bigint;
        fixedRate: bigint;
        percentDI: bigint;
        couponFrequencyDays: bigint;
        amortType: bigint;
        isinCode: string;
        cetipCode: string;
        series: string;
        hasRepactuacao: boolean;
        hasEarlyRedemption: boolean;
        comboId: string;
      }
    ],
    "view"
  >;

  totalAmortized: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  trustee: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vnaRecord: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        value: bigint;
        lastUpdateDate: bigint;
        lastIndexValue: bigint;
        accumulatedFactor: bigint;
      }
    ],
    "view"
  >;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  withdrawPaymentTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BLACKLISTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUSINESS_DAYS_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LOCK_UP_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NOT_WHITELISTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAUSED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION_PERCENT_DI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION_PU"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUCCESS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRUSTEE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WHITELIST_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedDIFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addToBlacklist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "amortizationSchedule"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        date: bigint;
        percentOrValue: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchAddToWhitelist"
  ): TypedContractMethod<[accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimAllCoupons"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCoupon"
  ): TypedContractMethod<[couponIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "couponClaimed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "couponRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        date: bigint;
        puPerUnit: bigint;
        totalAmount: bigint;
        distributed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "declareDefault"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "declareMaturity"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositPaymentTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "detectTransferRestriction"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "earlyRedemption"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeAmortization"
  ): TypedContractMethod<[scheduleIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAmortizationScheduleLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCouponCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingClaims"
  ): TypedContractMethod<[holder: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTerms"
  ): TypedContractMethod<
    [],
    [BrazilianDebentureCloneable.DebentureTermsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVNA"
  ): TypedContractMethod<
    [],
    [BrazilianDebentureCloneable.VNARecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      initName: string,
      initSymbol: string,
      initTerms: BrazilianDebentureCloneable.DebentureTermsStruct,
      initOracle: AddressLike,
      initPaymentToken: AddressLike,
      initIssuer: AddressLike,
      initTrustee: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastDIUpdateDate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "messageForTransferRestriction"
  ): TypedContractMethod<[restrictionCode: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordCoupon"
  ): TypedContractMethod<
    [puPerUnit: BigNumberish, totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeFromBlacklist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAmortizationSchedule"
  ): TypedContractMethod<
    [schedule: BrazilianDebentureCloneable.AmortizationScheduleStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "terms"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean,
        string
      ] & {
        vne: bigint;
        totalSupplyUnits: bigint;
        issueDate: bigint;
        maturityDate: bigint;
        anniversaryDay: bigint;
        lockUpEndDate: bigint;
        rateType: bigint;
        fixedRate: bigint;
        percentDI: bigint;
        couponFrequencyDays: bigint;
        amortType: bigint;
        isinCode: string;
        cetipCode: string;
        series: string;
        hasRepactuacao: boolean;
        hasEarlyRedemption: boolean;
        comboId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAmortized"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vnaRecord"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        value: bigint;
        lastUpdateDate: bigint;
        lastIndexValue: bigint;
        accumulatedFactor: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawPaymentTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AmortizationExecuted"
  ): TypedContractEvent<
    AmortizationExecutedEvent.InputTuple,
    AmortizationExecutedEvent.OutputTuple,
    AmortizationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BlacklistUpdated"
  ): TypedContractEvent<
    BlacklistUpdatedEvent.InputTuple,
    BlacklistUpdatedEvent.OutputTuple,
    BlacklistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CouponClaimed"
  ): TypedContractEvent<
    CouponClaimedEvent.InputTuple,
    CouponClaimedEvent.OutputTuple,
    CouponClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CouponRecorded"
  ): TypedContractEvent<
    CouponRecordedEvent.InputTuple,
    CouponRecordedEvent.OutputTuple,
    CouponRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DebentureInitialized"
  ): TypedContractEvent<
    DebentureInitializedEvent.InputTuple,
    DebentureInitializedEvent.OutputTuple,
    DebentureInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StatusChanged"
  ): TypedContractEvent<
    StatusChangedEvent.InputTuple,
    StatusChangedEvent.OutputTuple,
    StatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VNAUpdated"
  ): TypedContractEvent<
    VNAUpdatedEvent.InputTuple,
    VNAUpdatedEvent.OutputTuple,
    VNAUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "AmortizationExecuted(uint256,uint256)": TypedContractEvent<
      AmortizationExecutedEvent.InputTuple,
      AmortizationExecutedEvent.OutputTuple,
      AmortizationExecutedEvent.OutputObject
    >;
    AmortizationExecuted: TypedContractEvent<
      AmortizationExecutedEvent.InputTuple,
      AmortizationExecutedEvent.OutputTuple,
      AmortizationExecutedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BlacklistUpdated(address,bool)": TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;
    BlacklistUpdated: TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;

    "CouponClaimed(address,uint256,uint256)": TypedContractEvent<
      CouponClaimedEvent.InputTuple,
      CouponClaimedEvent.OutputTuple,
      CouponClaimedEvent.OutputObject
    >;
    CouponClaimed: TypedContractEvent<
      CouponClaimedEvent.InputTuple,
      CouponClaimedEvent.OutputTuple,
      CouponClaimedEvent.OutputObject
    >;

    "CouponRecorded(uint256,uint256,uint256)": TypedContractEvent<
      CouponRecordedEvent.InputTuple,
      CouponRecordedEvent.OutputTuple,
      CouponRecordedEvent.OutputObject
    >;
    CouponRecorded: TypedContractEvent<
      CouponRecordedEvent.InputTuple,
      CouponRecordedEvent.OutputTuple,
      CouponRecordedEvent.OutputObject
    >;

    "DebentureInitialized(string,uint256,uint256,uint8)": TypedContractEvent<
      DebentureInitializedEvent.InputTuple,
      DebentureInitializedEvent.OutputTuple,
      DebentureInitializedEvent.OutputObject
    >;
    DebentureInitialized: TypedContractEvent<
      DebentureInitializedEvent.InputTuple,
      DebentureInitializedEvent.OutputTuple,
      DebentureInitializedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StatusChanged(uint8,uint8)": TypedContractEvent<
      StatusChangedEvent.InputTuple,
      StatusChangedEvent.OutputTuple,
      StatusChangedEvent.OutputObject
    >;
    StatusChanged: TypedContractEvent<
      StatusChangedEvent.InputTuple,
      StatusChangedEvent.OutputTuple,
      StatusChangedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VNAUpdated(uint256,uint256,uint256)": TypedContractEvent<
      VNAUpdatedEvent.InputTuple,
      VNAUpdatedEvent.OutputTuple,
      VNAUpdatedEvent.OutputObject
    >;
    VNAUpdated: TypedContractEvent<
      VNAUpdatedEvent.InputTuple,
      VNAUpdatedEvent.OutputTuple,
      VNAUpdatedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
