[package]
name = "delos-oracle"
version = "0.1.0"
description = "BCB macroeconomic data oracle for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "delos_oracle"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "1.0.0"
