/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBrazilianMacroOracle,
  IBrazilianMacroOracleInterface,
} from "../../../contracts/BrazilianDebenture.sol/IBrazilianMacroOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "rateType",
        type: "string",
      },
    ],
    name: "getRate",
    outputs: [
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "realWorldDate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "rateType",
        type: "string",
      },
    ],
    name: "getRateMetadata",
    outputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "heartbeat",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "minAnswer",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "maxAnswer",
        type: "int256",
      },
      {
        internalType: "bool",
        name: "isActive",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBrazilianMacroOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IBrazilianMacroOracleInterface {
    return new Interface(_abi) as IBrazilianMacroOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBrazilianMacroOracle {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBrazilianMacroOracle;
  }
}
